" ----------------------------------------------------------------------------
"  General
" ----------------------------------------------------------------------------

set nocompatible
set noswapfile
set autoread               " reload files changed outside vim

" ----------------------------------------------------------------------------
"  Text Formatting
" ----------------------------------------------------------------------------

set autoindent             " automatic indent new lines
set smartindent            " be smart about it
set nowrap                 " do not wrap lines
set softtabstop=4          " four y'all
set shiftwidth=4           " ..
set tabstop=4              " ..
set expandtab              " expand tabs to spaces
set nosmarttab             " fuck tabs

" ----------------------------------------------------------------------------
"  Remapping
" ----------------------------------------------------------------------------

" disable arrow keys
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>
imap <up> <nop>
imap <down> <nop>
imap <left> <nop>
imap <right> <nop>

" fix fat fingers
command WQ wq
command Wq wq
command W w
command Q q

" ----------------------------------------------------------------------------
"  UI
" ----------------------------------------------------------------------------

syntax on                  " use syntax highlighting
set ruler                  " show the cursor position all the time
set nolazyredraw           " turn off lazy redraw
set cursorline             " highlight line cursor is on

" theme
set background=dark
colorscheme molokai

" unbroken lines between splits
hi VertSplit ctermbg=NONE ctermfg=14
set fillchars-=vert:\|
set fillchars+=vert:│

" ----------------------------------------------------------------------------
" Visual Cues
" ----------------------------------------------------------------------------

set hlsearch               " highlight search
set showmatch              " brackets/braces that is
set incsearch              " do incremental searching
set ignorecase             " ignore case when searching
set visualbell             " shut the fuck up
match Error /\%81v.\+/     " highlight >80 char lines

" display trailing spaces
set list listchars=tab:\ \ ,trail:·
