# ----------------------------------------------------------------------------
# General
# ----------------------------------------------------------------------------

set-option -g history-limit 10000
set-window-option -g monitor-activity on
set-window-option -g aggressive-resize on

# Automatically set window title
set-window-option -g automatic-rename

# Renumber tabs
set-option -g base-index 1
set-option -g renumber-windows on

# Show colors
set-option -g default-terminal "screen-256color"

# ----------------------------------------------------------------------------
# Interaction
# ----------------------------------------------------------------------------

# Move like vim
setw -g mode-keys vi
set -g status-keys vi

# Copy like vim
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection

set -g mouse on

set -g pane-active-border-style fg=blue

# ----------------------------------------------------------------------------
# Key Bindings
# ----------------------------------------------------------------------------

# first unbind, then bind: this allows on-the-fly config reloading (with C-r)
# quick tip: the '-r' flag means they can be pressed repeatedly


# window cycling
unbind <
bind -r < previous-window
unbind >
bind -r > next-window

